services:
  db:
    image: postgres:16
    container_name: energy_credit_db
    environment:
      POSTGRES_USER: ec_user
      POSTGRES_PASSWORD: ec_pass
      POSTGRES_DB: energy_credit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
